/** @format */

export const categoryConstants = {
  GET_ALL_CATEGORIES_REQUIEST: "GET_ALL_CATEGORIES_REQUIEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
  ADD_NEW_CATEGORY_REQUIEST: " ADD_NEW_CATEGORY_REQUIEST",
  ADD_NEW_CATEGORY_SUCCESS: " ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: " ADD_NEW_CATEGORY_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCTS_REQUIEST: " GET_ALL_PRODUCTS_REQUIEST",
  GET_ALL_PRODUCTS_SUCCESS: " GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: " GET_ALL_PRODUCTS_FAILURE",

  GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
  GET_PRODUCT_PAGE_REQUEST: "GET_PRODUCT_PAGE_REQUEST",
  GET_PRODUCT_PAGE_SUCCESS: "GET_PRODUCT_PAGE_SUCCESS",
  GET_PRODUCT_PAGE_FAILURE: "GET_PRODUCT_PAGE_FAILURE",

  GET_PRODUCTS_DETAILS_BY_ID_REQUEST: "GET_PRODUCTS_DETAILS_BY_ID_REQUEST",
  GET_PRODUCTS_DETAILS_BY_ID_SUCCESS: "GET_PRODUCTS_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCTS_DETAILS_BY_ID_FAILURE: "GET_PRODUCTS_DETAILS_BY_ID_FAILURE",

  FILTER_PRODUCTS_BY_PRICE: "FILTER_PRODUCTS_BY_PRICE",
  SORTING_PRODUCTS_BY_PRICE: "SORTING_PRODUCTS_BY_PRICE",
  SEARCH_PRODUCT_BY_NAME: "SEARCH_PRODUCT_BY_NAME",
};

export const authConstants = {
  LOGIN_REQUIEST: "LOGIN_REQUIEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUIEST: " LOGOUT_REQUIEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  PASSRESET_REQUEST: "PASSRESET_REQUEST",
  PASSRESET_SUCCESS: "PASSRESET_SUCCESS",
  PASSRESET_FAILURE: "PASSRESET_FAILURE",
};

export const cartConstants = {
  ADD_TO_CART_REQUEST: " ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: " ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: " ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};

export const wishlistConstants = {
  ADD_TO_WISHLIST_REQUEST: " ADD_TO_WISHLIST_REQUEST",
  ADD_TO_WISHLIST_SUCCESS: " ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE: " ADD_TO_WISHLIST_FAILURE",
  RESET_WISHLIST: "RESET_WISHLIST",

  REMOVE_WISHLIST_ITEM_REQUEST: "REMOVE_WISHLIST_ITEM_REQUEST",
  REMOVE_WISHLIST_ITEM_SUCCESS: "REMOVE_WISHLIST_ITEM_SUCCESS",
  REMOVE_WISHLIST_ITEM_FAILURE: "REMOVE_WISHLIST_ITEM_FAILURE",
};

export const userConstants = {
  GET_USER_ADDRESS_REQUEST: "GET_USER_ADDRESS_REQUEST ",
  GET_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS ",
  GET_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE ",

  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST ",
  ADD_USER_ADDRESS_SUCCESS: "GET_USER_ADDRESS_SUCCESS ",
  ADD_USER_ADDRESS_FAILURE: "GET_USER_ADDRESS_FAILURE ",

  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_ORDER_BY_PIN_REQUEST: "GET_USER_ORDER_BY_PIN_REQUEST",
  GET_USER_ORDER_BY_PIN_SUCCESS: "GET_USER_ORDER_BY_PIN_SUCCESS",
  GET_USER_ORDER_BY_PIN_FAILURE: "GET_USER_ORDER_BY_PIN_FAILURE",

  GET_USER_ORDER_DETAILS_REQUEST: "GET_USER_ORDER_DETAILS_REQUEST",
  GET_USER_ORDER_DETAILS_SUCCESS: "GET_USER_ORDER_DETAILS_SUCCESS",
  GET_USER_ORDER_DETAILS_FAILURE: "GET_USER_ORDER_DETAILS_FAILURE",

  CANCLE_USER_ORDER_REQUIEST: "CANCLE_USER_ORDER_REQUIEST",
  CANCLE_USER_ORDER_SUCCESS: "CANCLE_USER_ORDER_SUCCESS",
  CANCLE_USER_ORDER_FAILURE: "CANCLE_USER_ORDER_FAILURE",

  CANCLE_USER_PRODUCT_REQUIEST: "CANCLE_USER_PRODUCT_REQUIEST",
  CANCLE_USER_PRODUCT_SUCCESS: "CANCLE_USER_PRODUCT_SUCCESS",
  CANCLE_USER_PRODUCT_FAILURE: "CANCLE_USER_ORDER_FAILURE",
};

export const forgotPasswordConstants = {
  GET_FORGOT_PASSWORD_REQUEST: "GET_FORGOT_PASSWORD_REQUEST",
  GET_FORGOT_PASSWORD_SUCCESS: "GET_FORGOT_PASSWORD_SUCCESS",
  GET_FORGOT_PASSWORD_FAILURE: "GET_FORGOT_PASSWORD_FAILURE",

  GET_CHECK_OTP_REQUEST: "GET_CHECK_OTP_REQUEST",
  GET_CHECK_OTP_SUCCESS: "GET_CHECK_OTP_SUCCESS",
  GET_CHECK_OTP_FAILURE: "GET_CHECK_OTP_FAILURE",

  GET_CHANGE_PASSWORD_REQUEST: "GET_CHANGE_PASSWORD_REQUEST",
  GET_CHANGE_PASSWORD_SUCCESS: "GET_CHANGE_PASSWORD_SUCCESS",
  GET_CHANGE_PASSWORD_FAILURE: "GET_CHANGE_PASSWORD_FAILURE",
  GET_CHANGE_PASSWORD_ERROR: "GET_CHANGE_PASSWORD_ERROR",
};

export const changePasswordConstants = {
  GET_CHECK_PASSWORD_PAGE_REQUEST: "GET_CHECK_PASSWORD_PAGE_REQUEST",
  GET_CHECK_PASSWORD_PAGE_SUCCESS: "GET_CHECK_PASSWORD_PAGE_SUCCESS",
  GET_CHECK_PASSWORD_PAGE_FAILURE: "GET_CHECK_PASSWORD_PAGE_FAILURE",

  GET_CHANGE_PASSWORD_PAGE_REQUEST: "GET_CHANGE_PASSWORD_PAGE_REQUEST",
  GET_CHANGE_PASSWORD_PAGE_SUCCESS: "GET_CHANGE_PASSWORD_PAGE_SUCCESS",
  GET_CHANGE_PASSWORD_PAGE_FAILURE: "GET_CHANGE_PASSWORD_PAGE_FAILURE",
  GET_CHANGE_PASSWORD_PAGE_ERROR: "GET_CHANGE_PASSWORD_PAGE_ERROR",
};
